/**
 * CCA-F vocabulary deck - terms pulled from the ten mock exams and the Exam Guide.
 *
 * Hardcoded rather than stored in the database: this is reference content that only
 * changes when a new exam attempt surfaces new terms, which is a code change (a new
 * entry appended below), not a content-editing workflow that needs an admin form.
 *
 * Each item is `[term, meaning (vi), part of speech, example, example translation]`. A
 * tuple instead of an object keeps 290 entries scannable in one screen - a labelled
 * object per row would triple the line count for no information gain.
 *
 * ## Topics follow the exam's domains, subdivided to stay studiable
 *
 * The ten groups below are driven by the five scored CCA-F domains, but the two domains
 * that dominate the deck are split so no topic is a hundred-word wall: Agentic becomes
 * loop/orchestration, multi-agent/synthesis and action-safety; Tool/MCP splits into schema
 * design and error-and-ops; Prompt/Output splits into prompt craft and structured output.
 * A tenth group holds the business-scenario words (refund, warranty, ledger) that every
 * domain's questions lean on without any of them owning.
 *
 * They used to be fourteen groups carrying the shape of how the deck was assembled -
 * "Bổ sung - Đề 1", "Bổ sung - Đề 3-9" - which said where a word was found rather than
 * what it belongs to, and split Agentic Architecture across three separate lists.
 *
 * ## Every example is a real exam sentence
 *
 * The `ex` field quotes the question bank verbatim wherever the term appears there, so
 * the phrasing studied here is the phrasing the exam uses. The 92 entries that once
 * carried a Vietnamese gloss in that slot, with no English at all and no translation
 * below it, now carry both.
 */

export type VocabGroup = {
  cat: string
  items: [term: string, vi: string, pos: string, ex: string, exVi: string][]
}

export const VOCAB_DATA: VocabGroup[] = [
  {
    cat: 'Agentic - vòng lặp & điều phối',
    items: [
      ['prefetch', 'tải/lấy dữ liệu trước khi cần', 'v/n', 'your loop calls get_customer and lookup_order up front... prefetch', 'vòng lặp của bạn gọi get_customer và lookup_order ngay từ đầu... đó là prefetch'],
      ['steer', 'lái, chi phối (hướng suy luận của model)', 'v', 'so it steers its reasoning', 'khiến nó chi phối luôn cả cách model suy luận'],
      ['append(ed)', 'gắn/thêm vào (cuối)', 'v', 'appends both results before Claude\'s first turn', 'gắn cả hai kết quả vào trước lượt trả lời đầu tiên của Claude'],
      ['iteration', 'một vòng lặp (trong agent loop)', 'n', 'across two iterations', 'trải qua hai vòng lặp'],
      ['stop_reason', 'trường lý do dừng (trong API response)', 'n', 'Caching breaks the stop_reason sequence', 'Việc cache làm hỏng chuỗi giá trị stop_reason'],
      ['tool_use_id', 'mã định danh cho một lượt gọi tool', 'n', 'appended without a tool_use_id', 'được gắn vào mà thiếu tool_use_id'],
      ['stale(ness)', '(dữ liệu) cũ/lỗi thời', 'adj/n', 'The cache returns a stale result', 'Bộ nhớ đệm trả về một kết quả đã cũ'],
      ['context-limit error', 'lỗi vượt giới hạn ngữ cảnh (context window)', 'n phr', 'failed with a context-limit error', 'thất bại với lỗi vượt giới hạn ngữ cảnh'],
      ['cache(d)', 'bộ nhớ đệm / lưu đệm lại', 'n/v', 'the loop returns the earlier result... without marking it as cached', 'vòng lặp trả về kết quả trước đó... mà không đánh dấu là đã được cache'],
      ['prerequisite', 'điều kiện tiên quyết (phải xong trước mới được làm tiếp)', 'n', 'a programmatic prerequisite that blocks cancel_subscription until verify_account_holder has returned', 'một điều kiện tiên quyết bằng code chặn cancel_subscription cho tới khi verify_account_holder trả về kết quả'],
      ['self-reported confidence', 'độ tin cậy do chính model tự chấm', 'n phr', 'escalate whenever it self-reports a confidence score below 7 out of 10', 'leo thang bất cứ khi nào nó tự chấm điểm tin cậy dưới 7/10'],
      ['sentiment analysis', 'phân tích cảm xúc (từ văn bản)', 'n phr', 'supplement it with sentiment analysis to catch frustrated customers', 'bổ sung phân tích cảm xúc để phát hiện khách hàng đang bực bội'],
      ['exploratory (tool calls)', 'có tính dò tìm, khám phá trước khi hành động', 'adj', 'burns many exploratory tool calls listing and paging through issues', 'tốn rất nhiều lượt gọi tool mang tính dò tìm để liệt kê và lật qua từng trang issue'],
      ['paging through', 'duyệt/lật qua từng trang kết quả', 'v phr', 'listing and paging through issues just to discover which ones exist', 'liệt kê và lật từng trang issue chỉ để biết chúng tồn tại'],
      ['crowd out', 'chiếm chỗ, lấn át (khiến cái khác không còn chỗ)', 'v phr', 'these raw tool results accumulate and crowd out the context window', 'các kết quả tool thô này tích tụ lại và chiếm hết cửa sổ ngữ cảnh'],
      ['fork_session', 'API tách một phiên làm việc hiện tại thành nhánh mới', 'n', 'use the fork_session API to duplicate the session', 'dùng API fork_session để nhân bản phiên làm việc'],
      ['branch identifier', 'mã định danh của một nhánh (session đã fork)', 'n phr', 'send the branch identifier to the human operator', 'gửi mã định danh nhánh cho người vận hành'],
      ['normalization', 'sự chuẩn hóa (đưa các định dạng khác nhau về cùng một chuẩn)', 'n', 'where does this normalization belong?', 'việc chuẩn hóa này nên đặt ở đâu?'],
      ['checkpoint(ing)', 'điểm lưu tiến trình để có thể phục hồi khi gặp sự cố', 'n/v', 'the workflow checkpoints by running /compact at fixed intervals', 'quy trình lưu điểm kiểm tra bằng cách chạy /compact theo chu kỳ cố định'],
      ['manifest', 'tệp mô tả trạng thái/danh sách các phần việc đã hoàn thành', 'n', 'the coordinator replays that manifest on restart', 'coordinator phát lại bản mô tả trạng thái đó khi khởi động lại'],
      ['iteration cap / hard limit', 'giới hạn cứng cho số vòng lặp tối đa', 'n phr', 'set a hard limit of 8 iterations as the primary termination mechanism', 'đặt giới hạn cứng 8 vòng lặp làm cơ chế dừng chính'],
      ['backstop', 'biện pháp phòng hộ, chốt chặn cuối cùng (không phải cơ chế chính)', 'n', 'keeping the iteration cap only as a safety backstop', 'chỉ giữ giới hạn vòng lặp như một biện pháp phòng hộ an toàn'],
      ['termination mechanism', 'cơ chế xác định khi nào vòng lặp nên dừng', 'n phr', 'what is the correct way to control termination?', 'cách đúng để kiểm soát việc dừng là gì?'],
      ['misbehave', 'hoạt động sai lệch, không đúng như kỳ vọng', 'v', 'This misbehaves on requests that need none of those steps (e.g., a simple address change).', 'Cách này hoạt động sai lệch với những yêu cầu không cần bước nào trong số đó (ví dụ: một yêu cầu đổi địa chỉ đơn giản).'],
      ['edge case', 'trường hợp biên, tình huống hiếm/đặc biệt', 'n phr', 'Write a test suite covering the edge cases first, then feed failing output back to Claude.', 'Viết trước bộ test bao phủ các trường hợp biên, rồi đưa kết quả lỗi ngược lại cho Claude.'],
      ['decision tree', 'cây quyết định (chuỗi nhánh rẽ if/else)', 'n phr', 'Expand the decision tree with additional conditional branches to cover address changes, billing questions, and every other request type.', 'Mở rộng cây quyết định bằng các nhánh điều kiện bổ sung để bao phủ đổi địa chỉ, câu hỏi hóa đơn và mọi loại yêu cầu khác.'],
      ['conditional branch', 'nhánh rẽ có điều kiện', 'n phr', 'Expand the decision tree with additional conditional branches to cover address changes, billing questions, and every other request type.', 'Mở rộng cây quyết định bằng các nhánh điều kiện bổ sung để bao phủ đổi địa chỉ, câu hỏi hóa đơn và mọi loại yêu cầu khác.'],
      ['keyword-sensitive', 'dễ bị chi phối bởi một từ khóa cụ thể trong prompt', 'adj', 'Fix the keyword-sensitive system prompt line that pulls the agent toward web_search.', 'Sửa dòng system prompt nhạy từ khóa đang kéo agent nghiêng về phía web_search.'],
      ['canonical (format/status)', 'dạng chuẩn hóa, thống nhất duy nhất', 'adj', 'Add few-shot examples teaching the model to map every code and string to a canonical status.', 'Thêm các ví dụ few-shot dạy model ánh xạ mọi mã và chuỗi về một trạng thái chuẩn hóa duy nhất.'],
      ['required-args', 'tham số bắt buộc phải cung cấp (trong frontmatter skill)', 'n phr', 'Add a required-args array in the frontmatter that blocks execution until all parameters are supplied.', 'Thêm một mảng required-args trong frontmatter để chặn việc chạy cho tới khi mọi tham số được cung cấp đủ.'],
      ['wall-clock time', 'thời gian thực tế trôi qua (khác với thời gian xử lý CPU)', 'n phr', 'Give the run an overall budget in wall-clock time or iterations, ending it with whatever partial result exists.', 'Cấp cho lượt chạy một ngân sách tổng theo thời gian thực tế hoặc số vòng lặp, kết thúc nó với bất kỳ kết quả dở dang nào đang có.'],
      ['adaptive planning agent', 'agent lập kế hoạch một cách thích ứng theo tình huống', 'n phr', 'The scope is not known in advance, so someone proposes an adaptive planning agent.', 'Phạm vi công việc không biết trước, nên có người đề xuất dùng một agent lập kế hoạch thích ứng.'],
      ['release checklist', 'danh sách các bước cần kiểm tra trước khi phát hành', 'n phr', 'Your team wants an agent that automates a fixed four-step release checklist where every step is known in advance.', 'Đội của bạn muốn một agent tự động hóa danh sách kiểm tra phát hành cố định gồm bốn bước, trong đó mọi bước đều biết trước.'],
      ['fixed pipeline', 'một quy trình xử lý cố định, chạy giống nhau mọi lần bất kể input', 'n phr', 'Your returns agent runs a fixed pipeline: it always calls get_customer, then lookup_order, then check_policy.', 'Agent xử lý đổi trả của bạn chạy một quy trình cố định: luôn gọi get_customer, rồi lookup_order, rồi check_policy.'],
      ['dependency order', 'thứ tự phải tuân theo do có quan hệ phụ thuộc lẫn nhau', 'n phr', 'Run the steps in dependency order — settle the migration and the new name first, then fan out the dependent edits in parallel.', 'Chạy các bước theo đúng thứ tự phụ thuộc - chốt phần migration và tên mới trước, rồi mới phân tán song song các chỉnh sửa phụ thuộc.'],
    ],
  },
  {
    cat: 'Agentic - đa agent & tổng hợp',
    items: [
      ['coordinator', 'agent điều phối trung tâm', 'n', 'Your coordinator receives each subagent\'s structured findings', 'Coordinator của bạn nhận kết quả có cấu trúc từ mỗi subagent'],
      ['subagent', 'agent con do coordinator gọi ra', 'n', 'one searches the web, one analyzes documents', 'một subagent tìm kiếm trên web, một subagent phân tích tài liệu'],
      ['decomposition', 'sự phân rã (nhiệm vụ lớn thành phần nhỏ)', 'n', 'What does this show about decomposition?', 'Điều này cho thấy gì về việc phân rã nhiệm vụ?'],
      ['fan-out', 'phân tán ra nhiều nhánh chạy song song', 'n', 'the fan-out width must respect that limit', 'độ rộng phân tán song song phải tuân theo giới hạn đó'],
      ['contend (for a resource)', 'tranh giành (tài nguyên chung)', 'v', 'can still contend for one resource', 'vẫn có thể tranh giành cùng một tài nguyên'],
      ['rate-limited', 'bị giới hạn tốc độ gọi', 'adj', 'hit the same rate-limited registry API', 'cùng gọi vào một API registry bị giới hạn tốc độ'],
      ['dependency graph', 'sơ đồ/đồ thị các phụ thuộc lẫn nhau', 'n phr', 'the dependency graph must be mapped first', 'đồ thị phụ thuộc phải được lập sơ đồ trước'],
      ['synthesis / synthesize', 'sự tổng hợp / tổng hợp lại', 'n/v', 'pass the rewrite to synthesis', 'chuyển bản viết lại sang bước tổng hợp'],
      ['verbatim', 'nguyên văn, đúng từng chữ', 'adv', 'preserve every figure and citation verbatim', 'giữ nguyên văn mọi số liệu và trích dẫn'],
      ['fabricate(d)', 'bịa đặt, ngụy tạo (dữ liệu giả)', 'v/adj', 'A report contained a fabricated statistic', 'Một báo cáo chứa một số liệu bị bịa đặt'],
      ['diagnosable', 'có thể chẩn đoán/truy vết được', 'adj', 'changes that make the pipeline diagnosable', 'các thay đổi giúp pipeline có thể chẩn đoán được'],
      ['attribution', 'sự quy về nguồn gốc (ai/cái gì tạo ra)', 'n', 'keep that attribution through aggregation', 'giữ được sự quy kết nguồn gốc đó xuyên suốt quá trình tổng hợp'],
      ['aggregation', 'sự tổng hợp/gộp dữ liệu lại', 'n', 'through aggregation', 'qua bước tổng hợp/gộp dữ liệu'],
      ['reproduce (a run)', 'tái tạo lại (một lượt chạy) để kiểm tra', 'v', 'a run can be reproduced one subagent at a time', 'một lượt chạy có thể được tái tạo lại từng subagent một'],
      ['recency', 'tính mới/gần đây (của thông tin)', 'n', 'how many independent sources, and what recency', 'bao nhiêu nguồn độc lập, và độ mới của thông tin ra sao'],
      ['plausible', 'nghe có vẻ hợp lý (nhưng chưa chắc đúng)', 'adj', 'stop at the first two plausible sources', 'dừng lại ở hai nguồn đầu tiên nghe có vẻ hợp lý'],
      ['entity (HTML entity)', 'thực thể HTML (ký tự được mã hóa như &amp;)', 'n', 'returns HTML entities inside every snippet', 'trả về các thực thể HTML bên trong mỗi đoạn trích'],
      ['snippet', 'đoạn trích ngắn (văn bản/code)', 'n', 'reads the raw results and returns cleaned snippets', 'đọc kết quả thô và trả về các đoạn trích đã được làm sạch'],
      ['wrapper', 'lớp bọc bên ngoài (bao 1 thành phần khác)', 'n', 'a wrapper subagent', 'một subagent đóng vai trò lớp bọc'],
      ['post-processing', 'xử lý hậu kỳ (sau khi có kết quả)', 'n', 'a post-processing step over the finished report', 'một bước xử lý hậu kỳ trên báo cáo đã hoàn thành'],
      ['inherit(ing/ance)', 'kế thừa (nhận lại từ cấp cha)', 'v/n', 'rather than inheriting the parent\'s set', 'thay vì kế thừa bộ công cụ của agent cha'],
      ['synthesizable', 'có thể tổng hợp được', 'adj', 'mark the topic as not synthesizable', 'đánh dấu chủ đề là không thể tổng hợp được'],
      ['originate', 'bắt nguồn, khởi nguồn từ', 'v', 'which is where the number originates', 'đó chính là nơi con số này bắt nguồn'],
      ['primary source / secondary coverage', 'nguồn sơ cấp / nguồn đưa tin thứ cấp', 'n phr', 'excluding blogs and secondary coverage', 'loại trừ blog và các nguồn đưa tin thứ cấp'],
      ['quantify(ied)', 'định lượng (đưa ra con số cụ thể)', 'v/adj', 'any quantified claim that cannot be attributed', 'bất kỳ tuyên bố định lượng nào không thể quy về nguồn'],
      ['coarser (scale)', 'thang đo thô hơn, ít chi tiết hơn', 'adj', 'confidence on a coarser scale', 'độ tin cậy theo một thang đo thô hơn'],
      ['redundancy / redundant', 'sự dư thừa, trùng lặp không cần thiết', 'n/adj', 'the report wastes effort on duplicated findings... reduce this redundancy', 'báo cáo lãng phí công sức vào các phát hiện trùng lặp... cần giảm bớt sự dư thừa này'],
      ['partition (v)', 'phân chia phạm vi công việc cho từng bên phụ trách', 'v', 'partition the research scope across the subagents', 'chia phạm vi nghiên cứu ra cho các subagent'],
      ['subtopic', 'chủ đề con (nằm trong một chủ đề lớn)', 'n', 'assigning each a distinct subtopic or source type', 'giao cho mỗi subagent một chủ đề con hoặc loại nguồn riêng biệt'],
      ['coherent', 'mạch lạc, có tính liên kết chặt chẽ', 'adj', 'the synthesis is coherent but the section on cryptography is thin', 'bản tổng hợp mạch lạc nhưng phần về mật mã học lại sơ sài'],
      ['thin (section)', 'sơ sài, thiếu chiều sâu', 'adj', 'the section on cryptography is noticeably thin compared to the others', 'phần về mật mã học sơ sài rõ rệt so với các phần khác'],
      ['parametric knowledge', 'kiến thức nội tại của model (không tra cứu từ nguồn ngoài)', 'n phr', 'expand every thin section on its own using its parametric knowledge', 'tự mở rộng mọi phần sơ sài bằng chính kiến thức nội tại của model'],
      ['re-delegate', 'giao lại nhiệm vụ (cho một lượt/agent khác)', 'v', 're-delegate targeted queries until coverage is sufficient', 'giao lại các truy vấn có mục tiêu cụ thể cho tới khi độ bao phủ đủ'],
      ['relevance filtering', 'việc lọc theo mức độ liên quan', 'n phr', 'The document analysis subagent is discarding non-crop sources because of overly strict relevance filtering.', 'Subagent phân tích tài liệu đang loại bỏ các nguồn không thuộc mảng cây trồng vì bộ lọc mức độ liên quan quá chặt tay.'],
      ['deduplicate / dedupe', 'loại bỏ các mục trùng lặp', 'v', 'Post every finding and let the downstream script deduplicate by string comparison.', 'Đăng mọi phát hiện rồi để script ở phía sau khử trùng lặp bằng cách so sánh chuỗi.'],
      ['annotate', 'gắn chú thích, đánh dấu thêm thông tin', 'v', 'Report both values explicitly, annotated with their respective source attributions and publication dates.', 'Báo cáo rõ ràng cả hai giá trị, có chú thích kèm nguồn tương ứng và ngày công bố của từng giá trị.'],
      ['concatenate', 'nối chuỗi, ghép nhiều đoạn văn bản lại với nhau', 'v', 'Run all subagents one more time in parallel and concatenate the second-round outputs onto the first report.', 'Chạy lại tất cả subagent song song thêm một lượt nữa rồi nối kết quả vòng hai vào bản báo cáo đầu tiên.'],
      ['remit', 'phạm vi trách nhiệm được giao cho một agent/subagent', 'n', 'Instruct the subagent in its system prompt to return empty sections when the document does not fit its remit.', 'Hướng dẫn subagent ngay trong system prompt của nó trả về phần rỗng khi tài liệu không thuộc phạm vi trách nhiệm của nó.'],
      ['separation of concerns', 'nguyên tắc tách biệt các mối quan tâm/trách nhiệm', 'n phr', 'Exception handling belongs in the coordinator and recovery belongs in the subagent, and mixing the two breaks that separation of concerns.', 'Xử lý ngoại lệ thuộc về coordinator còn phục hồi lỗi thuộc về subagent; trộn lẫn hai việc đó là phá vỡ nguyên tắc tách biệt trách nhiệm.'],
    ],
  },
  {
    cat: 'Agentic - an toàn hành động & kiểm toán',
    items: [
      ['terminal exception', 'ngoại lệ nghiêm trọng làm dừng hẳn tiến trình', 'n phr', 'throw a terminal exception in the MCP server process', 'ném ra một ngoại lệ nghiêm trọng trong tiến trình server MCP'],
      ['transient (failure)', 'tạm thời, chỉ thoáng qua (không phải lỗi vĩnh viễn)', 'adj', 'transient and retryable, so the coordinator tries again after a backoff', 'tạm thời và có thể thử lại, nên coordinator thử lại sau một khoảng chờ'],
      ['eligibility', 'tính đủ điều kiện', 'n', 'Add a programmatic prerequisite that blocks issue_store_credit until eligibility is confirmed.', 'Thêm một điều kiện tiên quyết bằng code chặn issue_store_credit cho tới khi tính đủ điều kiện được xác nhận.'],
      ['return window', 'thời hạn được phép đổi/trả hàng', 'n phr', 'A refund is rejected because the order falls outside the 30-day return window.', 'Một yêu cầu hoàn tiền bị từ chối vì đơn hàng nằm ngoài thời hạn đổi trả 30 ngày.'],
      ['swallow (an exception)', 'bắt lỗi rồi bỏ qua, không báo cáo lên trên', 'v', 'Exception handling belongs in the coordinator, so a subagent that swallows its own errors leaves the only component with a view of the full workflow unaware of them.', 'Việc xử lý ngoại lệ thuộc về coordinator, nên một subagent tự nuốt lỗi của chính nó khiến thành phần duy nhất nhìn được toàn bộ quy trình không hay biết gì về chúng.'],
      ['suppress (a failure)', 'dập tắt/che giấu một lỗi thay vì xử lý', 'v', 'Suppressed failures become indistinguishable from genuine empty results, so the coordinator never learns there is anything to recover from.', 'Lỗi bị che giấu trở nên không thể phân biệt với kết quả rỗng hợp lệ, nên coordinator không bao giờ biết có gì cần khắc phục.'],
      ['indistinguishable', 'không thể phân biệt được với cái khác', 'adj', 'Suppressed failures become indistinguishable from genuine empty results.', 'Lỗi bị che giấu trở nên không thể phân biệt được với kết quả rỗng hợp lệ.'],
      ['drift', 'sự trôi dạt, lệch dần theo thời gian (quy ước, hành vi model)', 'n', 'A retry cap of one attempt, so a drifting prompt cannot multiply the cost of every pull request.', 'Giới hạn chỉ một lần thử lại, để một prompt đang trôi dạt không thể nhân chi phí của mọi pull request lên nhiều lần.'],
      ['injected (note)', 'bị chèn vào một cách không xác thực (có thể giả mạo)', 'adj', 'Keep the verification result in the conversation history but sign it, so the agent can tell a genuine note from an injected one.', 'Giữ kết quả xác minh trong lịch sử hội thoại nhưng ký lên nó, để agent phân biệt được ghi chú thật với ghi chú bị chèn vào.'],
      ['self-employed', 'tự kinh doanh, tự làm chủ (không làm công ăn lương)', 'adj', 'A manual audit reveals that self-employed applicants have a 30% error rate on tax forms.', 'Một đợt kiểm toán thủ công cho thấy hồ sơ của người tự kinh doanh có tỷ lệ lỗi 30% trên các biểu mẫu thuế.'],
      ['payroll', 'bảng lương, hồ sơ lương', 'n', 'We should have used stratified random sampling only on the high-confidence payroll extractions.', 'Lẽ ra chúng ta chỉ nên lấy mẫu ngẫu nhiên phân tầng trên các kết quả trích xuất bảng lương có độ tin cậy cao.'],
      ['segment (metrics)', 'phân khúc, chia nhỏ số liệu theo nhóm để đo riêng', 'v', 'We failed to segment the accuracy metrics by document type and applicant type prior to reducing human review.', 'Chúng ta đã không phân tách số liệu độ chính xác theo loại tài liệu và loại hồ sơ trước khi cắt giảm khâu review của con người.'],
      ['reconciliation', 'đối soát, đối chiếu số liệu giữa hai nguồn', 'n', 'Log the failed checks and let a reconciliation job flag any payout that was approved while the service was down.', 'Ghi log các lượt kiểm tra thất bại và để một job đối soát gắn cờ mọi khoản chi đã được duyệt trong lúc dịch vụ ngừng hoạt động.'],
      ['stratified random sampling', 'lấy mẫu ngẫu nhiên có phân tầng theo nhóm', 'n phr', 'Apply stratified random sampling of high-confidence extractions for periodic audit.', 'Áp dụng lấy mẫu ngẫu nhiên phân tầng trên các kết quả trích xuất có độ tin cậy cao để kiểm toán định kỳ.'],
      ['inflate (cost/latency)', 'làm phình to, đội chi phí hoặc độ trễ lên', 'v', 'The pipeline runs every step even when the question is simple, and this inflates latency and cost.', 'Pipeline chạy đủ mọi bước ngay cả khi câu hỏi rất đơn giản, và điều này làm đội cả độ trễ lẫn chi phí.'],
      ['blast radius', 'phạm vi ảnh hưởng khi có sự cố xảy ra', 'n phr', 'Reduce to 10 documents per request, which lowers the blast radius while keeping most of the batching benefit.', 'Giảm xuống 10 tài liệu mỗi request, cách này thu hẹp phạm vi ảnh hưởng khi có sự cố mà vẫn giữ được phần lớn lợi ích của xử lý theo lô.'],
      ['fraud signal', 'dấu hiệu cho thấy khả năng gian lận', 'n phr', 'Escalate at once: contradictory claims on one order are a fraud signal the agent is not equipped to judge.', 'Chuyển lên người xử lý ngay: hai lời khai mâu thuẫn trên cùng một đơn hàng là dấu hiệu gian lận mà agent không đủ khả năng phán đoán.'],
      ['idempotency / idempotency key', 'tính bất biến khi lặp lại thao tác (gọi lại nhiều lần không gây tác dụng phụ kép)', 'n', 'An idempotency key or the resulting credit ID, so a retry resolves to the existing credit instead of creating a second one.', 'Một idempotency key hoặc mã khoản tín dụng đã tạo, để lần thử lại trỏ về đúng khoản đã có thay vì tạo ra khoản thứ hai.'],
      ['speculative (call)', 'có tính suy đoán, thăm dò, chưa chắc chắn thực hiện', 'adj', 'Add a system-prompt rule telling the agent to confirm with the customer before every refund so a speculative call cannot happen unnoticed.', 'Thêm một quy tắc trong system prompt buộc agent xác nhận với khách trước mỗi lần hoàn tiền, để một lệnh gọi mang tính thăm dò không thể lọt qua mà không ai hay.'],
      ['confirmation turn', 'một lượt hội thoại dành riêng để xác nhận trước khi hành động', 'n phr', 'Keep both capabilities and add a confirmation turn in which the agent restates order number and amount before calling the credit tool.', 'Giữ cả hai khả năng và thêm một lượt xác nhận, trong đó agent nhắc lại mã đơn và số tiền trước khi gọi tool cấp tín dụng.'],
      ['fail closed / fail open', 'chặn lại khi có lỗi (an toàn) / cho qua khi có lỗi (kém an toàn)', 'n phr', 'Fail closed: an unavailable check blocks the payout and routes the case to human approval instead of allowing it.', 'Chặn lại khi có lỗi: một lượt kiểm tra không khả dụng sẽ chặn khoản chi và chuyển ca sang cho người duyệt thay vì cho qua.'],
      ['ownership (of a case)', 'quyền và trách nhiệm xử lý một ca/việc cụ thể', 'n', 'Transfer ownership: the agent stops acting on the case and routes further messages to the human queue.', 'Chuyển giao quyền xử lý: agent ngừng hành động trên ca đó và đẩy các tin nhắn tiếp theo sang hàng đợi của con người.'],
      ['escalation quota', 'hạn mức số ca được phép chuyển lên người xử lý', 'n phr', 'Set a daily escalation quota so the agent must prioritize which cases actually go to a human reviewer.', 'Đặt hạn mức chuyển tiếp mỗi ngày để agent buộc phải cân nhắc ưu tiên ca nào thực sự cần tới người xử lý.'],
    ],
  },
  {
    cat: 'Tool Design - schema & hợp đồng',
    items: [
      ['schema', 'lược đồ dữ liệu (định nghĩa cấu trúc)', 'n', 'your extraction schema', 'lược đồ trích xuất của bạn'],
      ['boolean', 'kiểu dữ liệu đúng/sai', 'n', 'taking a dry_run boolean', 'nhận vào một tham số boolean dry_run'],
      ['enum', 'kiểu liệt kê giá trị cố định', 'n', 'the flag should be an enum of preview and execute', 'cờ này nên là một enum gồm preview và execute'],
      ['description surface', 'phần mô tả (giúp model phân biệt tool)', 'n phr', 'reduces the description surface the model uses', 'làm giảm bề mặt mô tả mà model dùng để phân biệt'],
      ['destructive', 'có tính phá hủy/không thể hoàn tác', 'adj', 'makes the destructive path reachable', 'khiến nhánh có tính phá hủy trở nên dễ chạm tới'],
      ['payload', 'phần dữ liệu chính được truyền đi', 'n', 'returns isError: true with no payload', 'trả về isError: true mà không có payload'],
      ['render', 'hiển thị/dựng ra (trang, dữ liệu)', 'v', 'Page 3 fails to render', 'Trang 3 bị lỗi khi hiển thị/dựng'],
      ['placeholder', 'giá trị/chỗ giữ tạm', 'n', 'a placeholder for page 3', 'một giá trị giữ chỗ cho trang 3'],
      ['forced (tool_choice)', 'bị ép buộc gọi (không được tự chọn)', 'adj', 'You force extract_invoice', 'Bạn ép buộc gọi extract_invoice'],
      ['nullable', 'có thể mang giá trị null/rỗng', 'adj', 'Make purchase_order nullable', 'Cho phép purchase_order mang giá trị null'],
      ['register (PO register)', 'sổ đăng ký (danh sách tra cứu)', 'n', 'validate downstream against the PO register', 'đối chiếu kiểm tra ở downstream với sổ đăng ký PO'],
      ['downstream', 'ở phía sau (hệ thống tiêu thụ dữ liệu tiếp theo)', 'adj', 'downstream consumers', 'các hệ thống tiêu thụ dữ liệu ở phía sau'],
      ['dry_run', 'chạy thử, không thực thi thật', 'n', 'a refund tool taking a dry_run boolean', 'một tool hoàn tiền nhận vào tham số boolean dry_run'],
      ['distinguish', 'phân biệt', 'v', 'distinguish in the response between the fields that were retrieved', 'phân biệt trong phản hồi giữa các trường đã lấy được'],
      ['retrieve(d)', 'lấy về, truy xuất (dữ liệu)', 'v', 'the fields that were retrieved', 'các trường đã được truy xuất'],
      ['offset and limit', 'độ lệch (điểm bắt đầu) và giới hạn (khi đọc file)', 'n phr', 'Read that region with an offset and a limit', 'Đọc vùng đó bằng một độ lệch và một giới hạn'],
      ['anchor (non-unique)', 'điểm neo/tham chiếu (để Edit khớp vị trí)', 'n', 'three fail on non-unique anchors', 'ba lần thất bại vì điểm neo không duy nhất'],
      ['codemod', 'công cụ biến đổi mã nguồn tự động, hàng loạt', 'n', 'A codemod renames one config key across 45 files', 'Một codemod đổi tên một khóa cấu hình trên 45 file'],
      ['mechanical (transformation)', 'có tính máy móc, cơ học (không cần phán đoán)', 'adj', 'the transformation is mechanical', 'phép biến đổi này mang tính máy móc'],
      ['routing classifier', 'bộ phân loại dùng để định tuyến yêu cầu tới đúng chỗ', 'n phr', 'implement a routing classifier that inspects each request', 'triển khai một bộ phân loại định tuyến xem xét từng yêu cầu'],
      ['structured metadata', 'siêu dữ liệu có cấu trúc (đi kèm kết quả trả về)', 'n phr', 'as structured metadata', 'dưới dạng siêu dữ liệu có cấu trúc'],
      ['MCP resources', 'tài nguyên MCP - agent đọc trực tiếp, không cần gọi như tool', 'n phr', 'expose the issue summaries as MCP resources so the agent sees what is available', 'đưa các bản tóm tắt issue ra dưới dạng tài nguyên MCP để agent thấy được những gì đang có'],
      ['hardcoded', 'được viết cứng trực tiếp trong code/prompt (không linh hoạt)', 'adj', 'keep extending the hardcoded list of acceptable patterns', 'cứ tiếp tục mở rộng danh sách viết cứng các mẫu được chấp nhận'],
      ['deterministic', 'tất định - luôn cho ra cùng một kết quả với cùng đầu vào', 'adj', 'the model\'s pattern matching becomes stricter and more deterministic', 'việc khớp mẫu của model trở nên chặt chẽ và tất định hơn'],
      ['machine-parseable', 'có thể được máy tự động phân tích cú pháp, không cần con người đọc', 'adj', 'reliably machine-parseable with a guaranteed structure', 'có thể được máy phân tích cú pháp một cách đáng tin cậy nhờ cấu trúc được đảm bảo'],
      ['semantic search', 'tìm kiếm theo ngữ nghĩa (hiểu ý nghĩa, không chỉ khớp chữ)', 'n phr', 'Your wiki MCP server exposes wiki_search, which does semantic search across the whole knowledge base.', 'MCP server wiki của bạn cung cấp wiki_search, công cụ tìm kiếm theo ngữ nghĩa trên toàn bộ kho tri thức.'],
      ['literal matching', 'khớp theo nghĩa đen/nguyên văn chuỗi ký tự', 'n phr', 'Semantic search tools require tool_choice forcing, because the model cannot infer when semantic matching beats literal matching.', 'Các tool tìm kiếm ngữ nghĩa cần ép buộc bằng tool_choice, vì model không tự suy ra được khi nào khớp theo ngữ nghĩa tốt hơn khớp theo nghĩa đen.'],
    ],
  },
  {
    cat: 'MCP - lỗi, retry & vận hành',
    items: [
      ['retryable', 'có thể thử lại được', 'adj', 'marking page 3 as failed and whether it can be retried', 'đánh dấu trang 3 là lỗi và có thể thử lại hay không'],
      ['errorCategory', 'trường phân loại loại lỗi (transient / validation / permission)', 'n', 'include errorCategory and isRetryable flags as structured metadata', 'kèm theo errorCategory và cờ isRetryable dưới dạng siêu dữ liệu có cấu trúc'],
      ['permission failure', 'lỗi do thiếu quyền truy cập/thực hiện', 'n phr', 'distinguishing transient, validation and permission failures', 'phân biệt lỗi tạm thời, lỗi xác thực và lỗi thiếu quyền'],
      ['paywalled', 'có tường phí (phải trả tiền mới truy cập được)', 'adj', 'the account lacks access to a paywalled journal', 'tài khoản không có quyền truy cập vào một tạp chí có tường phí'],
      ['fatal error', 'lỗi nghiêm trọng khiến toàn bộ tiến trình phải dừng', 'n phr', 'a fatal error that terminates the entire research workflow immediately', 'một lỗi nghiêm trọng khiến toàn bộ quy trình nghiên cứu dừng lại ngay lập tức'],
      ['gateway timeout', 'hết thời gian chờ phản hồi từ cổng thanh toán/dịch vụ', 'n phr', 'Raise the gateway timeout so slow-but-successful calls return normally, and cap retries at one to bound the exposure.', 'Nâng thời gian chờ của cổng dịch vụ để các lệnh gọi chậm nhưng thành công vẫn trả về bình thường, và giới hạn chỉ một lần thử lại để chặn rủi ro.'],
      ['unindexed scan', 'quét dữ liệu không dùng index, rất chậm và tốn tài nguyên', 'n phr', 'Last week it ran an unindexed scan against the orders table during peak hours.', 'Tuần trước nó đã chạy một lượt quét không dùng index trên bảng orders vào đúng giờ cao điểm.'],
      ['read replica', 'bản sao chỉ đọc của cơ sở dữ liệu, tách khỏi bản chính', 'n phr', 'Keep sql_query but point it at a read replica, so an expensive query cannot affect production traffic.', 'Giữ sql_query nhưng trỏ nó sang một bản sao chỉ đọc, để một truy vấn tốn kém không thể ảnh hưởng tới lưu lượng production.'],
      ['statement timeout', 'giới hạn thời gian tối đa cho một câu truy vấn', 'n phr', 'Keep sql_query but point it at a read replica and set a statement timeout.', 'Giữ sql_query nhưng trỏ nó sang một bản sao chỉ đọc và đặt giới hạn thời gian cho mỗi câu truy vấn.'],
      ['LIMIT clause', 'mệnh đề giới hạn số dòng kết quả trả về (SQL)', 'n phr', 'Wrap sql_query in a hook that rejects statements without a LIMIT clause and logs the rest for the data team to review.', 'Bọc sql_query trong một hook từ chối các câu lệnh không có mệnh đề LIMIT và ghi log phần còn lại để đội dữ liệu xem lại.'],
      ['exponential backoff', 'độ trễ tăng dần theo cấp số nhân giữa các lần thử lại', 'n phr', 'Retry the decryption query 5 times with exponential backoff before returning a generic null result.', 'Thử lại truy vấn giải mã 5 lần với độ trễ tăng theo cấp số nhân trước khi trả về một kết quả null chung chung.'],
      ['headless (job/run)', 'chạy không có giao diện, không có người theo dõi trực tiếp', 'adj', 'It is loaded in every session — including headless CI runs — as the project context.', 'Nó được nạp trong mọi phiên làm việc - kể cả các lượt chạy CI không có giao diện - với vai trò ngữ cảnh của dự án.'],
      ['non-interactive', 'không cần/không chờ tương tác từ người dùng', 'adj', 'Bash commands are unavailable in non-interactive runs, so anything built on them breaks in CI.', 'Các lệnh Bash không khả dụng trong những lượt chạy không tương tác, nên mọi thứ dựng trên chúng đều hỏng khi lên CI.'],
      ['pin (a version/model)', 'ghim, cố định một phiên bản cụ thể', 'v', 'A model override pinning the skill to a more cautious model.', 'Một tùy chọn ghi đè model, ghim skill vào một model thận trọng hơn.'],
      ['masking (a field)', 'che/ẩn một phần dữ liệu nhạy cảm trước khi hiển thị', 'n/v', 'The masking hook must run before the audit hook, so what gets written to the store is the masked view of the result.', 'Hook che dữ liệu phải chạy trước hook kiểm toán, để thứ được ghi vào kho lưu trữ là bản đã che của kết quả.'],
      ['multi-tenant / brand scoping', 'kiến trúc phục vụ nhiều khách hàng/thương hiệu, cần phân vùng dữ liệu', 'n phr', 'A separate deployment per brand, so a session can only ever reach the data of the brand it was started for.', 'Mỗi thương hiệu một bản triển khai riêng, để một phiên làm việc chỉ có thể chạm tới dữ liệu của đúng thương hiệu mà nó được khởi tạo cho.'],
      ['role-scoped (subagent)', 'được giới hạn tool/quyền hạn theo đúng vai trò được giao', 'adj', 'Split the capabilities across role-scoped subagents, each holding only its own tools.', 'Chia nhỏ các năng lực ra thành những subagent giới hạn theo vai trò, mỗi cái chỉ giữ đúng bộ tool của mình.'],
      ['heterogeneous', 'không đồng nhất, đa dạng về hình thức/định dạng', 'adj', 'Add the hook — it is the standard place to normalize heterogeneous tool output before it reaches the model.', 'Thêm hook - đó là nơi tiêu chuẩn để chuẩn hóa kết quả tool không đồng nhất trước khi nó đến tay model.'],
      ['version pinning', 'việc ghim/cố định một phiên bản không cho tự động đổi', 'n phr', 'Pinning every MCP server to a fixed version in .mcp.json so behaviour cannot drift between clones.', 'Ghim mọi MCP server vào một phiên bản cố định trong .mcp.json để hành vi không thể trôi dạt giữa các bản clone.'],
      ['last line of defence', 'tuyến phòng thủ cuối cùng trước khi lỗi xảy ra thật sự', 'n phr', 'Nothing — the tool is the last line of defence and is the right place for both.', 'Không cần gì thêm - chính tool mới là tuyến phòng thủ cuối cùng và là nơi đúng đắn cho cả hai việc.'],
    ],
  },
  {
    cat: 'Prompt Engineering',
    items: [
      ['few-shot (examples)', 'ví dụ mẫu đưa kèm trong prompt để định hướng model', 'n phr', 'Your few-shot examples show the request and the tool chosen', 'Các ví dụ few-shot của bạn cho thấy yêu cầu và tool được chọn'],
      ['tie-breaking rule', 'quy tắc phân xử khi các lựa chọn ngang nhau', 'n phr', 'A tie-breaking rule stating which tool to prefer', 'Một quy tắc phân xử nêu rõ nên ưu tiên tool nào'],
      ['criteria', 'tiêu chí (đánh giá)', 'n', 'Your review criteria instruct the model to...', 'Tiêu chí review của bạn hướng dẫn model...'],
      ['inconsistent / consistency', 'không nhất quán / tính nhất quán', 'adj/n', 'Findings are inconsistent between runs', 'Các phát hiện không nhất quán giữa các lượt chạy'],
      ['convention', 'quy ước (coding convention)', 'n', 'flag anything that violates our conventions', 'gắn cờ bất cứ điều gì vi phạm quy ước của chúng ta'],
      ['infer', 'suy luận ra', 'v', 'infer the conventions from the surrounding code', 'suy luận ra quy ước từ code xung quanh'],
      ['severity', 'mức độ nghiêm trọng', 'n', 'Your severity levels are defined by code shape', 'Các mức độ nghiêm trọng của bạn được định nghĩa theo hình dạng code'],
      ['consequence', 'hậu quả', 'n', 'By consequence - what happens if this ships', 'Theo hậu quả - điều gì xảy ra nếu thứ này được triển khai'],
      ['worked example', 'ví dụ minh họa đầy đủ, chi tiết', 'n phr', 'with a worked example at each level', 'kèm một ví dụ minh họa chi tiết ở mỗi mức'],
      ['premise', 'tiền đề, giả định làm nền', 'n', 'a shared premise both agents trust', 'một tiền đề chung mà cả hai agent đều tin tưởng'],
      ['blind spot', 'điểm mù (chỗ không ai kiểm tra tới)', 'n', 'a blind spot no review pass will catch', 'một điểm mù mà không lượt review nào bắt được'],
      ['independent (review)', 'độc lập (không bị ảnh hưởng lẫn nhau)', 'adj', 'must be replaced by an independent instance', 'phải được thay bằng một instance độc lập'],
      ['trivial (change)', 'tầm thường, không đáng kể', 'adj', 'even one-line dependency bumps', 'kể cả những thay đổi tầm thường như nâng version một dòng'],
      ['route (by risk)', 'định tuyến/phân luồng theo mức rủi ro', 'v', 'Route by risk: full multi-pass review...', 'Định tuyến theo rủi ro: review nhiều lượt đầy đủ...'],
      ['mechanical check', 'kiểm tra máy móc, khách quan (không cần phán đoán)', 'n phr', 'a mechanical check has an objective answer', 'một kiểm tra máy móc có đáp án khách quan'],
      ['monolithic (system prompt)', 'nguyên khối, dồn hết mọi thứ vào một chỗ', 'adj', 'provide a monolithic system prompt listing every cache stampede failure scenario', 'cung cấp một system prompt nguyên khối liệt kê mọi kịch bản lỗi cache stampede'],
      ['forceful wording', 'lời lẽ mạnh mẽ, nhấn mạnh quá mức', 'n phr', 'rewrite the prose description with more forceful, detailed wording', 'viết lại phần mô tả bằng lời lẽ mạnh mẽ, chi tiết hơn'],
      ['interview pattern', 'kỹ thuật cho model hỏi lại làm rõ trước khi bắt tay vào làm', 'n phr', 'use the interview pattern: have Claude ask clarifying questions before writing code', 'dùng mẫu hình phỏng vấn: để Claude hỏi lại làm rõ trước khi viết code'],
      ['clarifying question(s)', 'câu hỏi nhằm làm rõ yêu cầu trước khi thực hiện', 'n phr', 'Claude ask clarifying questions before writing code', 'Claude đặt câu hỏi làm rõ trước khi viết code'],
      ['skim(ming)', 'đọc lướt qua, không đọc kỹ từng chi tiết', 'v', 'reviewers have started skimming the plans without reading them', 'người review đã bắt đầu đọc lướt các bản kế hoạch mà không đọc kỹ'],
      ['triage', 'phân loại và sắp xếp thứ tự ưu tiên xử lý', 'n/v', 'run a detection pass that reports everything, then a triage pass filtering on explicit criteria', 'chạy một lượt phát hiện báo cáo mọi thứ, sau đó một lượt phân loại ưu tiên lọc theo tiêu chí rõ ràng'],
      ['novel (variation)', 'mới lạ, chưa từng gặp trước đó', 'adj', 'still flags novel variations that are equally acceptable', 'vẫn gắn cờ những biến thể mới lạ dù chúng cũng chấp nhận được'],
      ['generalize', 'khái quát hóa để áp dụng được cho trường hợp mới, chưa thấy bao giờ', 'v', 'lets the model generalize to unseen-but-acceptable patterns', 'cho phép model khái quát hóa sang các mẫu chưa từng gặp nhưng vẫn chấp nhận được'],
      ['dismiss (a finding)', 'bác bỏ, gạt bỏ không xem xét', 'v', 'developers now dismiss roughly a third of all findings', 'giờ đây các lập trình viên bác bỏ khoảng một phần ba số phát hiện'],
      ['cross-file (issue)', 'lỗi/vấn đề liên quan đến nhiều file cùng lúc, không nằm gọn trong 1 file', 'adj phr', 'a separate integration pass focused on cross-file data flow', 'một lượt tích hợp riêng tập trung vào luồng dữ liệu xuyên nhiều file'],
      ['shallow vs deep (feedback)', 'phản hồi hời hợt, nông so với phản hồi sâu sắc, kỹ', 'adj', 'deep feedback on some files but shallow, contradictory feedback on others', 'phản hồi sâu sắc ở một số file nhưng hời hợt, mâu thuẫn ở những file khác'],
      ['prompt caching', 'cơ chế đệm lại phần prompt dùng chung để không phải trả tiền lại từ đầu', 'n phr', 'to optimize prompt caching, so the shared prefix is paid for once', 'để tối ưu việc đệm prompt, nhờ đó phần tiền tố dùng chung chỉ phải trả tiền một lần'],
      ['shared prefix', 'phần đầu của prompt giống nhau giữa nhiều lượt gọi', 'n phr', 'the shared prefix is paid for once rather than once per document', 'phần tiền tố dùng chung chỉ trả tiền một lần thay vì trả cho từng tài liệu'],
      ['idiomatic (code)', 'đúng phong cách tự nhiên, chuẩn mực của một ngôn ngữ lập trình', 'adj', 'The same prompt now runs on the Go and TypeScript packages, where it reports idiomatic error handling as a defect in almost every file.', 'Vẫn prompt đó giờ chạy trên các package Go và TypeScript, nơi nó báo cách xử lý lỗi đúng chuẩn ngôn ngữ là lỗi ở gần như mọi file.'],
      ['panel (review panel)', 'hội đồng gồm nhiều lượt/instance đánh giá song song', 'n phr', 'Raise the panel to five instances so the majority threshold is harder to reach by chance.', 'Nâng hội đồng review lên năm lượt chạy để ngưỡng đa số khó đạt được một cách ngẫu nhiên hơn.'],
      ['majority vote', 'biểu quyết theo số đông', 'n phr', 'Have a third reviewer break each tie by majority vote, then calibrate on the full set.', 'Để một lượt review thứ ba phá thế hòa bằng biểu quyết đa số, rồi hiệu chỉnh trên toàn bộ tập dữ liệu.'],
      ['checking lens', 'một góc nhìn/khía cạnh kiểm tra riêng biệt được giao cho mỗi lượt review', 'n phr', 'Give each pass a different checking lens — concurrency, data flow, error handling — instead of the same prompt three times.', 'Giao cho mỗi lượt review một góc nhìn kiểm tra khác nhau - tương tranh, luồng dữ liệu, xử lý lỗi - thay vì cùng một prompt lặp lại ba lần.'],
      ['disambiguate', 'làm rõ, phân biệt giữa các khả năng đang mơ hồ', 'v', 'Ask the customer for one more detail to disambiguate between the two matching records.', 'Hỏi khách thêm một chi tiết nữa để phân biệt rõ giữa hai bản ghi đang khớp trùng nhau.'],
    ],
  },
  {
    cat: 'Structured Output & đánh giá',
    items: [
      ['fabricated statistic', 'số liệu bịa đặt', 'n phr', 'A report contained a fabricated statistic', 'Một báo cáo chứa một số liệu bịa đặt'],
      ['calibrate(d)', 'hiệu chỉnh (để điểm số phản ánh đúng xác suất thật)', 'v/adj', 'cannot be read as a probability until it has been calibrated', 'không thể đọc như một xác suất cho tới khi được hiệu chỉnh'],
      ['threshold', 'ngưỡng (giá trị để ra quyết định)', 'n', 'auto-approving everything above 0.9', 'tự động duyệt mọi thứ trên ngưỡng 0.9'],
      ['ranking', 'sự xếp hạng', 'n', 'the scores are useful for ordering the review queue', 'điểm số hữu ích để sắp xếp thứ tự hàng đợi review'],
      ['ceiling', 'mức trần (giới hạn trên)', 'n', 'exceeds the ceiling that contract\'s own framework agreement allows', 'vượt quá mức trần mà chính hợp đồng khung của hợp đồng đó cho phép'],
      ['framework agreement', 'hợp đồng khung', 'n phr', 'the ceiling that contract\'s own framework agreement allows', 'mức trần mà hợp đồng khung của chính hợp đồng đó cho phép'],
      ['business-invariant', 'bất biến nghiệp vụ (quy tắc luôn đúng trong domain)', 'n phr', 'Business-invariant checks against the rules of the domain', 'Kiểm tra bất biến nghiệp vụ dựa trên quy tắc của lĩnh vực'],
      ['synchronous / asynchronous', 'đồng bộ / không đồng bộ', 'adj', 'the Message Batches API for the 50% saving', 'Message Batches API để tiết kiệm 50% chi phí'],
      ['SLA (service-level agreement)', 'thỏa thuận mức dịch vụ', 'n', 'would breach the team\'s SLA', 'sẽ vi phạm SLA của đội'],
      ['provenance', 'nguồn gốc xuất xứ (của dữ liệu)', 'n', 'every result carries its own provenance', 'mỗi kết quả mang theo nguồn gốc riêng của nó'],
      ['custom_id', 'mã định danh tùy chỉnh (gắn theo mỗi request)', 'n', 'The prompt version alongside each custom_id', 'Phiên bản prompt đi kèm mỗi custom_id'],
      ['backfill', 'lấp đầy dữ liệu cho các bản ghi cũ', 'v', 'backfill historical records with a default currency', 'lấp đầy dữ liệu lịch sử bằng một loại tiền tệ mặc định'],
      ['blank page / upside-down scan', 'trang trắng / bản scan bị lộn ngược', 'n phr', 'blank pages, upside-down scans, or the wrong document', 'trang trắng, bản scan bị lộn ngược, hoặc sai tài liệu'],
      ['pre-check', 'bước kiểm tra sơ bộ trước khi xử lý chính', 'n', 'Add a cheap pre-check that classifies the upload', 'Thêm một bước kiểm tra sơ bộ rẻ tiền để phân loại tệp tải lên'],
      ['classify', 'phân loại', 'v', 'classifies the upload before extraction', 'phân loại tệp tải lên trước khi trích xuất'],
      ['capacity', 'năng lực xử lý, công suất', 'n', 'Reviewer capacity is 1,200', 'Năng lực xử lý của người review là 1.200'],
      ['expire', 'hết hạn', 'v', '2,800 documents simply expire unreviewed', '2.800 tài liệu đơn giản là hết hạn mà chưa được review'],
      ['expected cost (of an error)', 'chi phí kỳ vọng (của một sai sót)', 'n phr', 'Rank the flagged documents by expected cost of an error', 'Xếp hạng các tài liệu bị gắn cờ theo chi phí kỳ vọng của một sai sót'],
      ['empirical', 'mang tính thực nghiệm (phải đo mới biết)', 'adj', 'The question is empirical, so it needs a measurement', 'Câu hỏi này mang tính thực nghiệm, nên cần một phép đo'],
      ['measurement', 'phép đo', 'n', 'a plan can lay out how to test it', 'một kế hoạch có thể vạch ra cách đo/kiểm tra điều đó'],
      ['appendix', 'phụ lục (phần thông tin bổ sung tách riêng)', 'n', 'a contract number that exists only in a separate appendix', 'một số hợp đồng chỉ tồn tại trong một phụ lục riêng'],
      ['cadence', 'nhịp độ, chu kỳ lặp lại đều đặn', 'n', 'submit batches on a fixed 4-hour cadence', 'gửi các lô theo nhịp cố định mỗi 4 giờ'],
      ['forgo', 'từ bỏ (một lợi ích) để đổi lấy thứ khác', 'v', 'forgoing the 50% batch discount', 'từ bỏ mức giảm giá 50% của xử lý theo lô'],
      ['coverage annotation', 'chú thích đánh dấu mức độ bao phủ thông tin (chỗ nào thiếu nguồn)', 'n phr', 'findings carrying coverage annotations that mark which subtopics are well-sourced', 'các phát hiện mang theo chú thích về độ bao phủ, đánh dấu chủ đề con nào có nguồn tốt'],
      ['freshness score', 'điểm số đánh giá độ mới của một số liệu/dữ liệu', 'n phr', 'add a numeric freshness score to each figure', 'thêm một điểm số đánh giá độ mới cho mỗi số liệu'],
      ['uniform (format)', 'đồng nhất, thống nhất về hình thức trình bày', 'adj', 'convert all findings to a single uniform format', 'chuyển mọi phát hiện về cùng một định dạng đồng nhất'],
      ['excerpt', 'đoạn trích dẫn ngắn từ nguồn gốc', 'n', 'structured findings (claim, excerpt, source URL)', 'các phát hiện có cấu trúc (tuyên bố, đoạn trích, URL nguồn)'],
      ['correlate(d)', 'có tương quan, liên kết được với nhau', 'v', 'tool results cannot be correlated to a custom_id in batch mode', 'kết quả tool không thể liên kết được với một custom_id trong chế độ xử lý theo lô'],
      ['qualifier', 'từ/cụm từ hạn định đi kèm một tuyên bố (VD: \'sơ bộ\', \'cỡ mẫu nhỏ\')', 'n', 'The qualifiers that bound the claim — preliminary, sample size — must travel with it as part of the claim.', 'Các từ hạn định ràng buộc tuyên bố - sơ bộ, cỡ mẫu - phải đi kèm nó như một phần của chính tuyên bố đó.'],
      ['sentinel (line)', 'một dòng/tín hiệu đặc biệt dùng để đánh dấu kết thúc rõ ràng', 'n', 'Instruct the model to end every extraction with a sentinel line, and have the loop return the record only when that line is present.', 'Hướng dẫn model kết thúc mọi lượt trích xuất bằng một dòng đánh dấu, và chỉ để vòng lặp trả về bản ghi khi dòng đó xuất hiện.'],
      ['ingestion', 'quá trình nạp/nhập dữ liệu vào hệ thống downstream', 'n', 'About 2% of documents produce a final record that stops mid-object, and ingestion stores the partial record as complete.', 'Khoảng 2% tài liệu tạo ra bản ghi cuối bị dừng giữa chừng, và khâu nạp dữ liệu lưu bản ghi dở dang đó như thể đã hoàn chỉnh.'],
      ['reproducibility', 'khả năng tái tạo lại được kết quả/quá trình', 'n', 'Without the exact prompt each subagent was spawned with, a disputed run loses its reproducibility.', 'Nếu không có đúng prompt mà mỗi subagent được khởi tạo cùng, một lượt chạy gây tranh cãi sẽ mất đi khả năng tái tạo lại.'],
      ['aspirational goal', 'mục tiêu mang tính khát vọng, chưa phải cam kết chắc chắn', 'n phr', 'A Japanese-language filing says a target is an aspirational goal, not a commitment.', 'Một hồ sơ tiếng Nhật ghi rằng chỉ tiêu đó là một mục tiêu mang tính khát vọng, không phải cam kết.'],
      ['native speaker review', 'việc để người bản xứ ngôn ngữ đó rà soát lại', 'n phr', 'That a native speaker review every finding drawn from a non-English source before it enters synthesis.', 'Rằng một người bản xứ phải rà soát mọi phát hiện lấy từ nguồn không phải tiếng Anh trước khi nó bước vào khâu tổng hợp.'],
      ['verifiability', 'khả năng kiểm chứng lại được một tuyên bố/số liệu', 'n', 'Normalizing the figure without keeping the original loses verifiability; select TWO changes that restore it.', 'Chuẩn hóa số liệu mà không giữ bản gốc sẽ đánh mất khả năng kiểm chứng; hãy chọn HAI thay đổi khôi phục lại điều đó.'],
      ['footnote', 'chú thích ở cuối trang/tài liệu', 'n', 'Add few-shot examples covering inline mentions, bibliographies, and footnotes.', 'Thêm các ví dụ few-shot bao phủ cả trích dẫn trong dòng, danh mục tài liệu tham khảo và chú thích cuối trang.'],
    ],
  },
  {
    cat: 'Claude Code, CI/CD & cấu hình',
    items: [
      ['boilerplate code', 'mã khuôn mẫu lặp đi lặp lại', 'n phr', 'generate boilerplate code', 'tạo ra mã khuôn mẫu lặp đi lặp lại'],
      ['repetitive', 'có tính lặp lại', 'adj', 'automate repetitive tasks', 'tự động hóa các tác vụ lặp đi lặp lại'],
      ['diff', 'phần khác biệt giữa 2 phiên bản code', 'n', 'positions in the diff', 'các vị trí trong diff'],
      ['inline (comment)', 'bình luận ngay tại dòng code', 'adj', 'avoiding inline positioning entirely', 'tránh hoàn toàn việc định vị bình luận trực tiếp tại dòng'],
      ['pre-pend', 'thêm vào ở đầu', 'v', 'Feed the model the diff with line numbers pre-pended', 'Đưa cho model bản diff đã có số dòng thêm vào đầu'],
      ['quoted (snippet/line)', 'được trích dẫn nguyên văn', 'adj', 'the quoted line text', 'đoạn văn bản dòng được trích dẫn'],
      ['generic (feedback)', 'chung chung, không cụ thể', 'adj', 'produces generic feedback', 'tạo ra phản hồi chung chung'],
      ['duplicate', 'trùng lặp', 'v/adj', 'suggests tests that duplicate existing fixtures', 'đề xuất các test trùng lặp với fixture đã có sẵn'],
      ['fixture', 'dữ liệu/thiết lập mẫu dùng để test', 'n', 'duplicate existing fixtures', 'trùng lặp với các fixture đã tồn tại'],
      ['readiness gate', 'ngưỡng/điều kiện xác nhận đã sẵn sàng', 'n phr', 'internal readiness gate of this site', 'ngưỡng sẵn sàng nội bộ của trang này'],
      ['glob (pattern)', 'mẫu khớp đường dẫn file (VD: **/*.ts)', 'n', 'Path rules support a branches field alongside paths', 'Rule theo đường dẫn hỗ trợ thêm trường branches bên cạnh paths'],
      ['exclusion', 'sự loại trừ', 'n', 'path rules cannot express exclusions', 'rule theo đường dẫn không thể diễn đạt việc loại trừ'],
      ['generated (files)', 'được sinh ra tự động (không viết tay)', 'adj', 'generated declaration files', 'các file khai báo được sinh tự động'],
      ['noise', 'nhiễu (thông tin thừa, gây phiền)', 'n', 'produce noise', 'tạo ra nhiễu'],
      ['regress(ion)', 'thoái lui - lỗi cũ xuất hiện trở lại', 'n', 'a case fixed two rounds ago breaks again', 'một trường hợp đã được sửa hai vòng trước lại bị lỗi trở lại'],
      ['supersede(d)', 'bị thay thế (bởi cái mới hơn)', 'adj', 'seven superseded attempts', 'bảy lần thử đã bị thay thế bởi lần sau'],
      ['converge/convergence', 'hội tụ (tiệm cận đến kết quả đúng)', 'n', 'convergence is likely', 'khả năng hội tụ (đến kết quả đúng) là cao'],
      ['scope (n)', 'phạm vi (của một thay đổi/nhiệm vụ)', 'n', 'scope is what makes a change plan-worthy', 'phạm vi mới là yếu tố khiến một thay đổi đáng để lập kế hoạch'],
      ['resync', 'đồng bộ hóa lại (sau khi có thay đổi)', 'v', 'run a Git reset to resync the workspace', 'chạy Git reset để đồng bộ lại không gian làm việc'],
      ['maintainable', 'dễ bảo trì, dễ duy trì lâu dài theo thời gian', 'adj', 'what is the most maintainable way to reorganize this configuration?', 'cách nào dễ bảo trì nhất để tổ chức lại cấu hình này?'],
      ['bloat(ing) / bloated', 'phình to, cồng kềnh một cách không cần thiết', 'adj/n', 'without duplicating content or bloating a single root file', 'mà không trùng lặp nội dung hay làm phình to một file gốc duy nhất'],
      ['monorepo', 'một kho mã nguồn chứa nhiều package/dự án con bên trong', 'n', 'you maintain a large monorepo where each package has its own coding standards', 'bạn duy trì một monorepo lớn, mỗi package có quy chuẩn code riêng'],
      ['modular', 'được chia theo từng khối/module riêng biệt, dễ tách rời', 'adj', 'keeping the configuration modular', 'giữ cho cấu hình theo dạng module hóa'],
      ['@import syntax', 'cú pháp import để kéo nội dung từ file khác vào (CLAUDE.md)', 'n phr', 'use the @import syntax in each package\'s CLAUDE.md', 'dùng cú pháp @import trong CLAUDE.md của mỗi package'],
      ['re-export', 'xuất lại một đối tượng dưới tên gọi khác (alias)', 'v', 'Grep for formatCurrency to find direct call sites and re-exporting modules.', 'Dùng Grep tìm formatCurrency để phát hiện các chỗ gọi trực tiếp và các module xuất lại nó.'],
      ['deprecated', 'đã lỗi thời, không còn được khuyến khích sử dụng', 'adj', 'A deprecated API is called in 30 places in this diff and your reviewer files 30 separate findings for it.', 'Một API đã lỗi thời được gọi ở 30 chỗ trong diff này và bộ review của bạn tạo ra 30 phát hiện riêng lẻ cho nó.'],
      ['durable fix', 'giải pháp khắc phục bền vững, lâu dài (không phải vá tạm)', 'n phr', 'The rule has to be enforced where it cannot be skipped; what is the correct durable fix?', 'Quy tắc phải được thực thi ở nơi không thể bỏ qua; đâu là giải pháp khắc phục bền vững đúng đắn?'],
      ['unwieldy', 'cồng kềnh, khó quản lý', 'adj', 'Your root CLAUDE.md has grown unwieldy: it mixes always-on coding standards with a long troubleshooting appendix.', 'File CLAUDE.md gốc của bạn đã trở nên cồng kềnh: nó trộn lẫn các quy chuẩn code luôn cần với một phụ lục xử lý sự cố dài dằng dặc.'],
      ['proportionate', 'tương xứng, phù hợp với mức độ của vấn đề', 'adj', 'A one-line dependency bump does not deserve the full review pipeline; what is the proportionate response?', 'Một thay đổi nâng version một dòng không đáng phải qua cả quy trình review đầy đủ; đâu là phản ứng tương xứng?'],
      ['hidden coupling', 'sự phụ thuộc/ràng buộc ngầm, khó nhận ra giữa các phần code', 'n phr', 'Your agent must add tests to a legacy service with no coverage and heavy hidden coupling.', 'Agent của bạn phải viết test cho một dịch vụ cũ không có độ bao phủ nào và đầy những ràng buộc ngầm.'],
      ['reversible', 'có thể đảo ngược lại được', 'adj', 'Every migration must be reversible before it is applied, so a bad deploy can be rolled back.', 'Mọi migration đều phải có thể đảo ngược trước khi được áp dụng, để một lần deploy hỏng có thể được quay lui.'],
      ['troubleshooting appendix', 'phụ lục hướng dẫn xử lý sự cố', 'n phr', 'Move the troubleshooting appendix into documentation the agent reads on request.', 'Chuyển phụ lục xử lý sự cố sang tài liệu mà agent chỉ đọc khi có yêu cầu.'],
      ['happy-path (test)', 'kịch bản kiểm thử lý tưởng, không có lỗi/ngoại lệ', 'n phr', 'Claude produced a parser that passes your happy-path tests but mishandles nested quotes.', 'Claude tạo ra một bộ phân tích cú pháp vượt qua mọi test kịch bản lý tưởng nhưng lại xử lý sai dấu ngoặc lồng nhau.'],
      ['ceremony', 'thủ tục rườm rà, tốn công sức không tương xứng', 'n', 'Keep the mandate but let developers approve their own plans for changes under ten lines, so the ceremony is shorter for small work.', 'Giữ quy định bắt buộc nhưng cho phép lập trình viên tự duyệt kế hoạch của mình với các thay đổi dưới mười dòng, để thủ tục nhẹ đi với việc nhỏ.'],
    ],
  },
  {
    cat: 'Context Management & Reliability',
    items: [
      ['interleave(d)', 'xen kẽ (trộn lẫn vào nhau)', 'v/adj', 'The file now interleaves the two investigations', 'Tệp giờ đây xen kẽ lẫn nhau giữa hai cuộc điều tra'],
      ['attributable', 'có thể quy về (ai đã viết/tạo ra)', 'adj', 'the sections stay attributable', 'các phần vẫn có thể quy về đúng người/nguồn tạo ra'],
      ['scratchpad', 'sổ nháp riêng (không chung với agent khác)', 'n', 'Give each subagent its own scratchpad', 'Cho mỗi subagent một sổ nháp riêng'],
      ['concurrent(ly)', 'đồng thời, cùng lúc', 'adj/adv', 'not safe for concurrent use', 'không an toàn khi dùng đồng thời'],
      ['serialize', 'tuần tự hóa (làm lần lượt, không song song)', 'v', 'Serialize the exploration so only one subagent writes at a time', 'Tuần tự hóa việc khám phá để chỉ một subagent ghi tại một thời điểm'],
      ['context window', 'cửa sổ ngữ cảnh (dung lượng model nhớ được)', 'n phr', 'would consume most of the context window', 'sẽ chiếm phần lớn cửa sổ ngữ cảnh'],
      ['summarize', 'tóm tắt', 'v', 'Summarize the document once', 'Tóm tắt tài liệu một lần'],
      ['vague(r)', 'mơ hồ hơn, mờ nhạt hơn', 'adj', 'answers have become vaguer', 'các câu trả lời đã trở nên mơ hồ hơn'],
      ['degrade / degradation', 'suy giảm (chất lượng phản hồi giảm dần theo thời gian/ngữ cảnh)', 'v/n', 'context degradation: keep key findings in a scratchpad file', 'suy giảm ngữ cảnh: hãy giữ các phát hiện quan trọng trong một sổ nháp'],
      ['obsolete', 'lỗi thời, không còn giá trị sử dụng', 'adj', 'the model has cached obsolete file diffs', 'model đã lưu đệm những bản diff file đã lỗi thời'],
      ['namespace', 'không gian tên riêng (phạm vi đặt tên/lưu trữ tách biệt)', 'n', 'both subagents read from a shared memory namespace that persists between invocations', 'cả hai subagent đều đọc từ một không gian tên bộ nhớ dùng chung, tồn tại xuyên suốt các lần gọi'],
      ['backoff (period)', 'khoảng thời gian chờ trước khi thử lại', 'n phr', 'the coordinator tries again after a backoff period', 'coordinator thử lại sau một khoảng thời gian chờ'],
      ['truncation window', 'giới hạn cắt bớt lịch sử hội thoại chỉ giữ N tin nhắn gần nhất', 'n phr', 'Raise the truncation window from six messages to twenty so more history survives each request.', 'Nâng cửa sổ cắt bớt từ sáu tin nhắn lên hai mươi để nhiều lịch sử hội thoại sống sót qua mỗi request hơn.'],
      ['hang (a call hangs)', 'bị treo, không phản hồi và không kết thúc', 'v', 'Reduce the number of tools the agent may call, so a hanging backend can only be reached through one of them.', 'Giảm số tool mà agent được phép gọi, để một backend bị treo chỉ có thể bị chạm tới qua đúng một trong số đó.'],
      ['abandon (mid-way)', 'bỏ dở giữa chừng, chưa hoàn tất', 'v', 'Compliance needs an audit record for every refund and credit the agent attempts, including the ones it abandons mid-way.', 'Bộ phận tuân thủ cần một bản ghi kiểm toán cho mọi khoản hoàn tiền và tín dụng mà agent thử thực hiện, kể cả những khoản nó bỏ dở giữa chừng.'],
      ['policy handbook', 'sổ tay/tài liệu chính sách đầy đủ', 'n phr', 'Every turn of your support agent carries the full 9,000-token policy handbook so the agent \'always knows the rules\'.', 'Mỗi lượt của agent hỗ trợ đều mang theo trọn bộ sổ tay chính sách 9.000 token để agent "luôn nắm được luật".'],
      ['narrative (summary)', 'bản tóm tắt theo lối kể chuyện, tường thuật', 'n', 'Move the narrative to the end of the file so the rules appear first and benefit from position effects.', 'Chuyển phần tường thuật xuống cuối file để các quy tắc xuất hiện trước và hưởng lợi từ hiệu ứng vị trí.'],
      ['corrupt (data)', 'làm hỏng, làm sai lệch dữ liệu', 'v', 'Summarize every twenty turns instead, so fewer summarization passes can corrupt data.', 'Thay vào đó hãy tóm tắt sau mỗi hai mươi lượt, để ít lượt tóm tắt hơn có cơ hội làm sai lệch dữ liệu.'],
      ['shortlist (v)', 'lập danh sách rút gọn các ứng viên tiềm năng', 'v', 'Read the three shortlisted papers in full once the candidate set is small.', 'Đọc toàn văn ba bài báo đã lọt danh sách rút gọn khi tập ứng viên đã đủ nhỏ.'],
      ['corpus', 'kho ngữ liệu/tài liệu tổng hợp để tìm kiếm', 'n', 'Your research pipeline has search_arxiv, search_pubmed and search_ssrn, each with a clear description of its corpus.', 'Pipeline nghiên cứu của bạn có search_arxiv, search_pubmed và search_ssrn, mỗi cái kèm mô tả rõ ràng về kho ngữ liệu của nó.'],
      ['inventory (file inventory)', 'danh mục kiểm kê đầy đủ (VD: danh sách file)', 'n', 'Bash, running a recursive directory listing to build a file inventory.', 'Dùng Bash, chạy một lệnh liệt kê thư mục đệ quy để dựng nên danh mục kiểm kê file.'],
      ['retention window / policy', 'khoảng thời gian hoặc chính sách lưu trữ dữ liệu', 'n phr', 'The retention window, and what an empty result means — absence of hits is not absence of events.', 'Khoảng thời gian lưu trữ, và ý nghĩa của một kết quả rỗng - không có kết quả khớp không đồng nghĩa với không có sự kiện nào xảy ra.'],
      ['best-effort', 'nỗ lực tối đa nhưng không đảm bảo chắc chắn 100%', 'adj', 'A note that log results are best-effort, so the agent hedges its wording whenever it reports on log data.', 'Một ghi chú rằng kết quả log chỉ mang tính nỗ lực tối đa, để agent nói có chừng mực mỗi khi báo cáo dựa trên dữ liệu log.'],
    ],
  },
  {
    cat: 'Bối cảnh nghiệp vụ & vận hành',
    items: [
      ['ambiguity / ambiguous', 'tính mơ hồ / mơ hồ, không rõ ràng', 'adj/n', 'The agent handles high-ambiguity requests like returns, billing disputes, and account issues.', 'Agent xử lý các yêu cầu có độ mơ hồ cao như đổi trả hàng, tranh chấp hóa đơn và các vấn đề về tài khoản.'],
      ['resolution', 'sự giải quyết, xử lý xong việc', 'n', 'target 80%+ first-contact resolution', 'mục tiêu giải quyết xong ngay từ lần liên hệ đầu tiên đạt trên 80%'],
      ['escalate / escalation', 'leo thang, chuyển lên cấp xử lý cao hơn', 'v/n', 'escalate_to_human; the human who picks it up', 'escalate_to_human; người tiếp nhận ca được chuyển lên'],
      ['dispute', 'tranh chấp, khiếu nại', 'n', 'billing disputes', 'các tranh chấp về hóa đơn/thanh toán'],
      ['handoff', 'sự bàn giao (công việc/case)', 'n', 'What must the handoff include?', 'Bản bàn giao phải bao gồm những gì?'],
      ['goodwill credit', 'khoản bồi hoàn thiện chí (không bắt buộc theo hợp đồng)', 'n', 'the agent already issued a $40 goodwill credit', 'agent đã cấp một khoản bồi hoàn thiện chí 40 đô trước đó'],
      ['ledger', 'sổ cái (ghi chép tài chính)', 'n', 'verify the ledger before taking any financial action', 'kiểm tra sổ cái trước khi thực hiện bất kỳ hành động tài chính nào'],
      ['warranty', 'bảo hành', 'n', 'check_warranty has run', 'check_warranty đã được gọi chạy'],
      ['consumable', 'hàng tiêu hao (dùng 1 lần, không có bảo hành lâu dài)', 'n/adj', 'For consumable items there is no warranty to check', 'Với hàng tiêu hao thì không có bảo hành để kiểm tra'],
      ['override', 'sự ghi đè, quyền vượt qua quy tắc mặc định', 'n/v', 'Provide an audited override so an agent can proceed', 'Cung cấp một cơ chế ghi đè có kiểm toán để agent có thể tiếp tục xử lý'],
      ['documented exception', 'ngoại lệ có ghi lại lý do', 'n phr', 'a documented exception, with the reason recorded', 'một ngoại lệ được ghi lại, kèm lý do được lưu vết'],
      ['condition-aware', 'có nhận biết theo điều kiện (không áp dụng cứng nhắc)', 'adj', 'Make the gate condition-aware', 'Làm cho cổng chặn có nhận biết theo điều kiện'],
      ['audit entry / audit trail', 'bản ghi kiểm toán / dấu vết kiểm toán', 'n', 'an audit entry for every refund attempt', 'một bản ghi kiểm toán cho mỗi lần thử hoàn tiền'],
      ['sympathy', 'sự thương cảm', 'n', 'refunding out of sympathy rather than policy', 'hoàn tiền vì thương cảm chứ không phải theo đúng chính sách'],
      ['motivation', 'động cơ, lý do hành động', 'n', 'not the motivation behind it', 'chứ không phải động cơ đằng sau hành động đó'],
      ['enforcement', 'sự thực thi (quy tắc)', 'n', 'enforcement must happen inside the tool', 'việc thực thi quy tắc phải nằm bên trong chính tool'],
      ['forecasting service', 'dịch vụ dự báo', 'n phr', 'a delivery estimate from a separate forecasting service', 'một ước tính thời gian giao hàng từ một dịch vụ dự báo riêng biệt'],
      ['non-essential dependency', 'phụ thuộc không thiết yếu', 'n phr', 'a non-essential dependency cannot fail the call', 'một phụ thuộc không thiết yếu không được phép làm hỏng cả lệnh gọi'],
      ['queue', 'hàng đợi', 'n', 'The queue is closed until 8am', 'Hàng đợi đóng cửa cho tới 8 giờ sáng'],
      ['silence / silently', 'sự im lặng / một cách âm thầm', 'n/adv', 'the customer waits in silence for six hours', 'khách hàng phải chờ trong im lặng suốt sáu tiếng'],
    ],
  },
]

export type VocabWord = {
  /** Stable 1-based position in the flattened deck, for display only. */
  order: number
  cat: string
  term: string
  vi: string
  pos: string
  ex: string
  exVi: string
}

/** Flattened once at module load; every view (flashcards, browse list) filters this. */
export const VOCAB_DECK: VocabWord[] = VOCAB_DATA.flatMap(group =>
  group.items.map(([term, vi, pos, ex, exVi]) => ({ term, vi, pos, ex, exVi, cat: group.cat, order: 0 }))
).map((word, i) => ({ ...word, order: i + 1 }))

export const VOCAB_CATEGORIES: string[] = VOCAB_DATA.map(group => group.cat)
