import mongoose, { Schema, type Types } from 'mongoose'

import { compileModel } from '@/lib/mongoose-model'
import {
  FORMS,
  MEANINGS,
  SHAPES,
  STATUSES,
  type Form,
  type InkBBox,
  type InkPoint,
  type Meaning,
  type Shape,
  type Status,
  type TodoRow,
} from '@/lib/whiteboard/limits'

/**
 * One thing on the whiteboard: a card, a to-do list, a shape, a frame or an ink stroke.
 *
 * ```
 *   form     text | todo | shape | frame | ink     what it IS on the canvas (fixed at create)
 *   meaning  dream | goal | failure | draft | note  what it SAYS about the owner (or null)
 *   status   active | someday | done | dropped      only next to dream / goal, else null
 *   parentId a frame's _id, or null                 x/y are RELATIVE to that frame when set
 * ```
 *
 * ## Why every item is its own document
 *
 * The picture is how things get in; the items and links are the product (design premise 1).
 * A single scene blob would make "search my failures" a full-board parse and would make one
 * card's privacy flag a field inside someone else's write. Per-item documents let the text
 * index, the meaning index and the privacy filter all run in Mongo.
 *
 * ## `_id` is generated by the CLIENT
 *
 * So a link or an edit can reference a card before its create has landed, and so a retried
 * create is an idempotent upsert rather than a duplicate. See `useSaveQueue`.
 *
 * ## `ink.bbox` is derived, never accepted (D27)
 *
 * `data.ts` recomputes it from the points on every write. Every agent read projects the
 * points OUT and works from the box alone - a stroke is ~50 KB of points and the export
 * preview reads the board every 400 ms.
 */

export type WhiteboardItemDocument = {
  _id: Types.ObjectId
  form: Form
  meaning: Meaning | null
  status: Status | null
  title: string
  body: string
  todos: TodoRow[]
  shape: Shape | null
  ink: { points?: InkPoint[]; bbox: InkBBox } | null
  parentId: Types.ObjectId | null
  x: number
  y: number
  width: number
  height: number
  z: number
  tags: string[]
  when: Date | null
  targetBy: Date | null
  includeInAi: boolean
  createdAt: Date
  updatedAt: Date
}

const todoSchema = new Schema<TodoRow>(
  {
    id: { type: String, required: true },
    text: { type: String, default: '' },
    done: { type: Boolean, default: false },
  },
  { _id: false }
)

const bboxSchema = new Schema<InkBBox>(
  {
    minX: { type: Number, required: true },
    minY: { type: Number, required: true },
    maxX: { type: Number, required: true },
    maxY: { type: Number, required: true },
  },
  { _id: false }
)

const inkSchema = new Schema(
  {
    points: { type: [[Number]], default: undefined },
    bbox: { type: bboxSchema, required: true },
  },
  { _id: false }
)

const whiteboardItemSchema = new Schema<WhiteboardItemDocument>(
  {
    _id: { type: Schema.Types.ObjectId, required: true },
    form: { type: String, enum: FORMS, required: true },
    meaning: { type: String, enum: [...MEANINGS, null], default: null },
    status: { type: String, enum: [...STATUSES, null], default: null },
    title: { type: String, default: '' },
    body: { type: String, default: '' },
    todos: { type: [todoSchema], default: [] },
    shape: { type: String, enum: [...SHAPES, null], default: null },
    ink: { type: inkSchema, default: null },
    parentId: { type: Schema.Types.ObjectId, default: null },
    x: { type: Number, default: 0 },
    y: { type: Number, default: 0 },
    width: { type: Number, default: 240 },
    height: { type: Number, default: 120 },
    z: { type: Number, default: 0 },
    tags: { type: [String], default: [] },
    when: { type: Date, default: null },
    targetBy: { type: Date, default: null },
    includeInAi: { type: Boolean, default: true },
  },
  { collection: 'whiteboard_items', timestamps: true, versionKey: false }
)

/*
  `default_language: 'none'`: no stemming and no stopword list. The board is mixed Vietnamese
  and English, and the English stemmer would both mangle Vietnamese tokens and drop words
  like "not" that change what a failure card means. Text index v3 is already diacritic-
  insensitive, which is what makes "muc tieu" find "mục tiêu".
*/
whiteboardItemSchema.index(
  { title: 'text', body: 'text', tags: 'text', 'todos.text': 'text' },
  { name: 'whiteboard_text', default_language: 'none' }
)
whiteboardItemSchema.index({ meaning: 1, status: 1 })
whiteboardItemSchema.index({ parentId: 1 })
whiteboardItemSchema.index({ form: 1, includeInAi: 1 })
whiteboardItemSchema.index({ updatedAt: -1 })

export const WhiteboardItemModel: mongoose.Model<WhiteboardItemDocument> =
  compileModel('WhiteboardItem', whiteboardItemSchema)
